services:
  api-gympass-pg:
    image: bitnami/postgresql
    container_name: adopet-pg
    environment:
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_DATABASE: adopet-api
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "docker"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: adopet-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      api-gympass-pg:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://docker:docker@api-gympass-pg:5432/adopet-api
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    # Volume para desenvolvimento - permite hot reload
    volumes:
      - .:/app
      - /app/node_modules