version: "3"

services:
  api-gympass-pg:
    image: bitnami/postgresql
    container_name: adopet-pg
    environment:
      POSTGRES_PASSWORD: docker # Definindo a senha do usuário postgres
      POSTGRES_USER: docker # Definindo o nome de usuário postgres (opcional)
      POSTGRES_DB: adopet-api # Definindo o nome do banco de dados
    ports:
      - "15432:5432" # Mapeamento da porta do contêiner para a porta do host