services:
  api:
    container_name: adopet-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      api-gympass-pg:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres.vztgjmeiojctpibbzjlz:jHo3wgVR50M9VFtf@aws-0-us-east-1.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1&pool_timeout=20
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    # Volume para desenvolvimento - permite hot reload
    volumes:
      - .:/app
      - /app/node_modules